describe('Arithmetic`s equals', () => {
  it('add commands', () => {
    cy.visit('/calculator')
    cy.contains('1').click()
    cy.get('.display').should('have.value', '1')
    cy.contains('+').click()
    cy.get('.display').should('have.value', '')
    cy.contains('2').click()
    cy.get('.display').should('have.value', '2')
    cy.get('.equal').click()
    cy.get('.display').should('have.attr', 'placeholder', '3')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
  })

  it('multiply commands', () => {
    cy.contains('3').click()
    cy.get('.display').should('have.value', '3')
    cy.contains('*').click()
    cy.get('.display').should('have.value', '')
    cy.contains('4').click()
    cy.get('.display').should('have.value', '4')
    cy.get('.equal').click()
    cy.get('.display').should('have.attr', 'placeholder', '12')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
  })

  it('subtract commands', () => {
    cy.contains('5').click()
    cy.get('.display').should('have.value', '5')
    cy.contains('-').click()
    cy.get('.display').should('have.value', '')
    cy.contains('6').click()
    cy.get('.display').should('have.value', '6')
    cy.get('.equal').click()
    cy.get('.display').should('have.attr', 'placeholder', '-1')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
    cy.get('.history').children().contains('5 - 6')
  })

  it('divide commands', () => {
    cy.contains('7').click()
    cy.get('.display').should('have.value', '7')
    cy.contains('/').click()
    cy.get('.display').should('have.value', '')
    cy.contains('8').click()
    cy.get('.display').should('have.value', '8')
    cy.get('.equal').click()
    cy.get('.display').should('have.attr', 'placeholder', '0.875')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
    cy.get('.history').children().contains('5 - 6')
    cy.get('.history').children().contains('7 / 8')
  })

  it('remainder of the division commands', () => {
    cy.contains('9').click()
    cy.get('.display').should('have.value', '9')
    cy.contains('%').click()
    cy.get('.display').should('have.value', '')
    cy.contains('1').click()
    cy.contains('0').click()
    cy.get('.display').should('have.value', '10')
    cy.get('.equal').click()
    cy.get('.display').should('have.attr', 'placeholder', '9')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
    cy.get('.history').children().contains('5 - 6')
    cy.get('.history').children().contains('7 / 8')
  })

  it('clear display', () => {
    cy.contains('1').click()
    cy.contains('1').click()
    cy.get('.display').should('have.value', '11')
    cy.contains('-').click()
    cy.get('.display').should('have.value', '')
    cy.contains('1').click()
    cy.contains('2').click()
    cy.get('.display').should('have.value', '12')
    cy.get('button').contains('C').click()
    cy.get('.display').should('have.value', '')
    cy.contains('1').click()
    cy.contains('3').click()
    cy.get('.display').should('have.value', '13')
    cy.get('.equal').click()
    cy.get('.display').should('have.attr', 'placeholder', '-2')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
    cy.get('.history').children().contains('5 - 6')
    cy.get('.history').children().contains('7 / 8')
    cy.get('.history').children().contains('9 % 10')
  })

  it('clear expression', () => {
    cy.contains('1').click()
    cy.contains('4').click()
    cy.get('.display').should('have.value', '14')
    cy.contains('+').click()
    cy.get('.display').should('have.value', '')
    cy.contains('1').click()
    cy.contains('5').click()
    cy.get('.display').should('have.value', '15')
    cy.get('button').contains('CE').click()
    cy.get('.display').should('have.value', '')
    cy.get('.display').should('have.attr', 'placeholder', '0')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
    cy.get('.history').children().contains('5 - 6')
    cy.get('.history').children().contains('7 / 8')
    cy.get('.history').children().contains('9 % 10')
  })

  it('sign change command', () => {
    cy.contains('1').click()
    cy.contains('6').click()
    cy.get('.display').should('have.value', '16')
    cy.contains('±').click()
    cy.get('.display').should('have.attr', 'placeholder', '-16')
    cy.get('.display').should('have.value', '')
    cy.get('.history').children().contains('1 + 2')
    cy.get('.history').children().contains('3 * 4')
    cy.get('.history').children().contains('5 - 6')
    cy.get('.history').children().contains('7 / 8')
    cy.get('.history').children().contains('9 % 10')
  })

  it('clear all', () => {
    cy.visit('/settings')
    cy.contains('Clear All History').click()
    cy.visit('/calculator')
    cy.get('.display').should('have.value', '')
    cy.get('.display').should('have.attr', 'placeholder', '0')
    cy.get('.history').children().should('have.length', 2)
  })
})
